version: '2'
services:
  odoo:
    build: ./odoo/
    volumes:
      - "data-odoo:/data/odoo"
    depends_on:
      - db
    environment:
      - SCENARIO_MAIN_TAG=depiltech
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=admin
      - LIMIT_TIME_CPU=5000
      - LIMIT_TIME_REAL=5000
      - RUNNING_ENV=dev
      - DEMO=False

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"

  # can be useful for dev when longpolling is required
  nginx:
    image: camptocamp/odoo-nginx:9.0
    depends_on:
      - odoo

volumes:
  data-odoo:
  data-db:
