version: '2'

services:
  odoo:
    tty: true
    stdin_open: true
    ports:
      - 8069
      - 8072
    volumes:
      - "./odoo/src:/opt/odoo/src"
      - "./odoo/local-src:/opt/odoo/local-src"
      - "./odoo/external-src:/opt/odoo/external-src"
      - "./odoo/songs:/opt/odoo/songs"
      - "./odoo/features:/opt/odoo/features"
      - "./odoo/migration.yml:/opt/odoo/migration.yml"
      - "./odoo/data:/opt/odoo/data"
    environment:
      - RUNNING_ENV=dev
      - MARABUNTA_MODE=demo  # could be 'demo' for the minimal db or 'full' for the complete one
      - MARABUNTA_ALLOW_SERIE=True  # should not be set in production

  db:
    ports:
      - 5432

  nginx:
    ports:
      - 80:80
